### ISSUE TITLE
About I3D feature

### ISSUE THREAD

**Issue by xljh0520** [zmzhang2000/MIGCN#1]
Hi, thanks for releasing the code! I have a question about the Charades I3D feature. 
Did you extract the I3D feature by yourself? If so, could you share more detail about the feature extractor?

**Comment by zmzhang2000** [comment]
@xljh0520 We extract the I3D feature using [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d). 

Please refer to the `README` of [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) for the feature extraction procedure.

**Comment by xljh0520** [comment]
> @xljh0520 We extract the I3D feature using [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d).
> 
> Please refer to the `README` of [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) for the feature extraction procedure.

Thanks for your reply. I run the [extract_features.py](https://github.com/piergiaj/pytorch-i3d/blob/master/extract_features.py) in [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) using the [rgb_charades.pt](https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_charades.pt). The feature shape matches yours, but it's not exactly the same as yours numerically.  
Could you share more detail and help me with this?

**Comment by zmzhang2000** [comment]
> > @xljh0520 We extract the I3D feature using [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d).
> > Please refer to the `README` of [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) for the feature extraction procedure.
> 
> Thanks for your reply. I run the [extract_features.py](https://github.com/piergiaj/pytorch-i3d/blob/master/extract_features.py) in [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) using the [rgb_charades.pt](https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_charades.pt). The feature shape matches yours, but it's not exactly the same as yours numerically. Could you share more detail and help me with this?

I also ran the [extract_features.py](https://github.com/piergiaj/pytorch-i3d/blob/master/extract_features.py) in [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) **again** using [rgb_charades.pt](https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_charades.pt), and I got **similar** features with our provided I3D feature.

In addition, please check the input source: [Charades_v1_rgb.tar](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades_v1_rgb.tar) and [charades.json](https://github.com/piergiaj/super-events-cvpr18/blob/master/data/charades.json).

There exist differences (less than ±0.01) between different run results. This may be caused by different Python/PyTorch/CUDA version and other randomness. It is hard to get exactly the same features.

**Comment by Wyz2927** [comment]
> > @xljh0520 We extract the I3D feature using [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d).
> > Please refer to the `README` of [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) for the feature extraction procedure.
> 
> Thanks for your reply. I run the [extract_features.py](https://github.com/piergiaj/pytorch-i3d/blob/master/extract_features.py) in [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) using the [rgb_charades.pt](https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_charades.pt). The feature shape matches yours, but it's not exactly the same as yours numerically. Could you share more detail and help me with this?

hello, could you provide me with your extracted i3d features on charades? I have tried to run the code in pytorch_i3d. But due to resource constrain, I only get the poor-quality features. I will be grateful if you can provide me the features. My email is wyz2927@163.com. Thank you very much!

**Comment by Wyz2927** [comment]
> > @xljh0520 We extract the I3D feature using [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d).
> > Please refer to the `README` of [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) for the feature extraction procedure.
> 
> Thanks for your reply. I run the [extract_features.py](https://github.com/piergiaj/pytorch-i3d/blob/master/extract_features.py) in [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) using the [rgb_charades.pt](https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_charades.pt). The feature shape matches yours, but it's not exactly the same as yours numerically. Could you share more detail and help me with this?

hello, could you provide me with your extracted i3d features on charades? I have tried to run the code in pytorch_i3d. But due to resource constrain, I only get the poor-quality features. I will be grateful if you can provide me the features. My email is wyz2927@163.com. Thank you very much!

**Comment by zmzhang2000** [comment]
> > > @xljh0520 We extract the I3D feature using [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d).
> > > Please refer to the `README` of [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) for the feature extraction procedure.
> > 
> > 
> > Thanks for your reply. I run the [extract_features.py](https://github.com/piergiaj/pytorch-i3d/blob/master/extract_features.py) in [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) using the [rgb_charades.pt](https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_charades.pt). The feature shape matches yours, but it's not exactly the same as yours numerically. Could you share more detail and help me with this?
> 
> hello, could you provide me with your extracted i3d features on charades? I have tried to run the code in pytorch_i3d. But due to resource constrain, I only get the poor-quality features. I will be grateful if you can provide me the features. My email is [wyz2927@163.com](mailto:wyz2927@163.com). Thank you very much!

We provide the Google Drive link to the i3d feature on charades in [README](https://github.com/zmzhang2000/MIGCN#charades-sta).

Feel free to download and use these features.

**Comment by Wyz2927** [comment]
> > > > @xljh0520 We extract the I3D feature using [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d).
> > > > Please refer to the `README` of [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) for the feature extraction procedure.
> > > 
> > > 
> > > Thanks for your reply. I run the [extract_features.py](https://github.com/piergiaj/pytorch-i3d/blob/master/extract_features.py) in [pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) using the [rgb_charades.pt](https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_charades.pt). The feature shape matches yours, but it's not exactly the same as yours numerically. Could you share more detail and help me with this?
> > 
> > 
> > hello, could you provide me with your extracted i3d features on charades? I have tried to run the code in pytorch_i3d. But due to resource constrain, I only get the poor-quality features. I will be grateful if you can provide me the features. My email is [wyz2927@163.com](mailto:wyz2927@163.com). Thank you very much!
> 
> We provide the Google Drive link to the i3d feature on charades in [README](https://github.com/zmzhang2000/MIGCN#charades-sta).
> 
> Feel free to download and use these features.

谢谢大佬提供特征，感激不尽！！
